/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class thanatos_ndkccalljava_JNI */

#ifndef _Included_thanatos_ndkccalljava_JNI
#define _Included_thanatos_ndkccalljava_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     thanatos_ndkccalljava_JNI
 * Method:    callBackAdd
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_thanatos_ndkccalljava_JNI_callBackAdd
  (JNIEnv *, jobject);

/*
 * Class:     thanatos_ndkccalljava_JNI
 * Method:    callBackFromJava
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_thanatos_ndkccalljava_JNI_callBackFromJava
  (JNIEnv *, jobject);

/*
 * Class:     thanatos_ndkccalljava_JNI
 * Method:    callBackPrintString
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_thanatos_ndkccalljava_JNI_callBackPrintString
  (JNIEnv *, jobject);

/*
 * Class:     thanatos_ndkccalljava_JNI
 * Method:    callBackSayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_thanatos_ndkccalljava_JNI_callBackSayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
